version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal
    networks:
      - app-network
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"


  app:
    build: .
    image: asma589/next-app:v3
    container_name: next-app
    ports:
      - "3000:3000"
    environment:
      AWS_REGION: "local"
      AWS_ACCESS_KEY_ID: "fakeMyKeyId"
      AWS_SECRET_ACCESS_KEY: "fakeSecretAccessKey"
      DYNAMODB_ENDPOINT:  "http://dynamodb:8000"

    depends_on:
      - dynamodb
    networks:
      - app-network

volumes:
  dynamodb_data:

networks:
  app-network:
    driver: bridge
